version: "3"

volumes:
  inventory-db-vol:

services:
  api:
    container_name: inventory_api
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file: 
      - .env
    depends_on:
      - db
    restart: always

  db:
    container_name: inventory_db_host
    image: mysql:5.7
    restart: always
    ports:
      - 32000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - inventory-db-vol:/var/lib/mysql
