version: "3"

volumes:
  supplytransaction-db-vol:

services:
  api:
    container_name: supplytransaction_api
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 5001:5000
    env_file: 
      - .env
    depends_on:
      - db
    restart: always

  db:
    container_name: supplytransaction_db_host
    image: mysql:5.7
    restart: always
    ports:
      - 32001:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: supplytransaction_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - supplytransaction-db-vol:/var/lib/mysql
